[2024-12-07T21:52:51.499+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T21:52:51.519+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:50:59.684629+00:00 [queued]>
[2024-12-07T21:52:51.531+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:50:59.684629+00:00 [queued]>
[2024-12-07T21:52:51.533+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T21:52:51.550+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-12-07 21:50:59.684629+00:00
[2024-12-07T21:52:51.556+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1329) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T21:52:51.559+0000] {standard_task_runner.py:72} INFO - Started process 1331 to run task
[2024-12-07T21:52:51.558+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_s3', 'load_to_s3', 'manual__2024-12-07T21:50:59.684629+00:00', '--job-id', '616', '--raw', '--subdir', 'DAGS_FOLDER/dag2_kafka_s3.py', '--cfg-path', '/tmp/tmpn3o1376r']
[2024-12-07T21:52:51.561+0000] {standard_task_runner.py:105} INFO - Job 616: Subtask load_to_s3
[2024-12-07T21:52:51.619+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:50:59.684629+00:00 [running]> on host d7d86e3077c3
[2024-12-07T21:52:51.736+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T21:50:59.684629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T21:50:59.684629+00:00'
[2024-12-07T21:52:51.738+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T21:52:51.769+0000] {logging_mixin.py:190} INFO - <class 'NoneType'>
[2024-12-07T21:52:51.770+0000] {logging_mixin.py:190} INFO - No messages to process
[2024-12-07T21:52:51.770+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T21:52:51.781+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T21:52:51.782+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_s3, task_id=load_to_s3, run_id=manual__2024-12-07T21:50:59.684629+00:00, execution_date=20241207T215059, start_date=20241207T215251, end_date=20241207T215251
[2024-12-07T21:52:51.815+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T21:52:51.834+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T21:52:51.836+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
