[2024-12-04T09:40:36.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T09:40:36.068+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_read.consume_from_topic manual__2024-12-04T09:40:34.034426+00:00 [queued]>
[2024-12-04T09:40:36.088+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_read.consume_from_topic manual__2024-12-04T09:40:34.034426+00:00 [queued]>
[2024-12-04T09:40:36.089+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T09:40:36.119+0000] {taskinstance.py:2889} INFO - Executing <Task(ConsumeFromTopicOperator): consume_from_topic> on 2024-12-04 09:40:34.034426+00:00
[2024-12-04T09:40:36.127+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=834) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T09:40:36.130+0000] {standard_task_runner.py:72} INFO - Started process 835 to run task
[2024-12-04T09:40:36.132+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_read', 'consume_from_topic', 'manual__2024-12-04T09:40:34.034426+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/dag2_Kafkas3.py', '--cfg-path', '/tmp/tmp89jxjtwg']
[2024-12-04T09:40:36.137+0000] {standard_task_runner.py:105} INFO - Job 205: Subtask consume_from_topic
[2024-12-04T09:40:36.225+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_read.consume_from_topic manual__2024-12-04T09:40:34.034426+00:00 [running]> on host 31ac0cc6adcb
[2024-12-04T09:40:36.438+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_read' AIRFLOW_CTX_TASK_ID='consume_from_topic' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T09:40:34.034426+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T09:40:34.034426+00:00'
[2024-12-04T09:40:36.442+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T09:40:36.498+0000] {base.py:84} INFO - Retrieving connection 'consume_kafka'
[2024-12-04T09:41:36.506+0000] {consume.py:167} INFO - Reached end of log. Exiting.
[2024-12-04T09:41:36.508+0000] {consume.py:182} INFO - committing offset at end_of_operator
[2024-12-04T09:41:36.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T09:41:36.529+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kafka_read, task_id=consume_from_topic, run_id=manual__2024-12-04T09:40:34.034426+00:00, execution_date=20241204T094034, start_date=20241204T094036, end_date=20241204T094136
[2024-12-04T09:41:36.572+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T09:41:36.594+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T09:41:36.597+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
