[2024-12-09T08:49:01.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T08:49:01.791+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_kafka_avro.read_from_minio manual__2024-12-09T08:48:58.509057+00:00 [queued]>
[2024-12-09T08:49:01.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_kafka_avro.read_from_minio manual__2024-12-09T08:48:58.509057+00:00 [queued]>
[2024-12-09T08:49:01.809+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T08:49:01.836+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): read_from_minio> on 2024-12-09 08:48:58.509057+00:00
[2024-12-09T08:49:01.845+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1074) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T08:49:01.848+0000] {standard_task_runner.py:72} INFO - Started process 1075 to run task
[2024-12-09T08:49:01.848+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_kafka_avro', 'read_from_minio', 'manual__2024-12-09T08:48:58.509057+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag3_s3_kafka.py', '--cfg-path', '/tmp/tmpc0z9uxtl']
[2024-12-09T08:49:01.855+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask read_from_minio
[2024-12-09T08:49:01.938+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_kafka_avro.read_from_minio manual__2024-12-09T08:48:58.509057+00:00 [running]> on host c23cf8b5bd6f
[2024-12-09T08:49:02.181+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_kafka_avro' AIRFLOW_CTX_TASK_ID='read_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T08:48:58.509057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T08:48:58.509057+00:00'
[2024-12-09T08:49:02.185+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T08:49:02.553+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-09T08:49:02.662+0000] {logging_mixin.py:190} INFO - Содержимое бакета reciept-bucket:
[2024-12-09T08:49:02.664+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T08:49:02.679+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T08:49:02.679+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=s3_to_kafka_avro, task_id=read_from_minio, run_id=manual__2024-12-09T08:48:58.509057+00:00, execution_date=20241209T084858, start_date=20241209T084901, end_date=20241209T084902
[2024-12-09T08:49:02.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T08:49:02.730+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T08:49:02.732+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
