[2024-12-03T19:39:37.264+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T19:39:37.283+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_to_kafka.send_to_kafka manual__2024-12-03T19:39:31.547969+00:00 [queued]>
[2024-12-03T19:39:37.293+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_to_kafka.send_to_kafka manual__2024-12-03T19:39:31.547969+00:00 [queued]>
[2024-12-03T19:39:37.293+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T19:39:37.309+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-12-03 19:39:31.547969+00:00
[2024-12-03T19:39:37.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=519) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T19:39:37.316+0000] {standard_task_runner.py:72} INFO - Started process 520 to run task
[2024-12-03T19:39:37.316+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mongo_to_kafka', 'send_to_kafka', 'manual__2024-12-03T19:39:31.547969+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag1_MongoKafka.py', '--cfg-path', '/tmp/tmpe_d9i58o']
[2024-12-03T19:39:37.319+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask send_to_kafka
[2024-12-03T19:39:37.364+0000] {task_command.py:467} INFO - Running <TaskInstance: mongo_to_kafka.send_to_kafka manual__2024-12-03T19:39:31.547969+00:00 [running]> on host 31ac0cc6adcb
[2024-12-03T19:39:37.457+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_to_kafka' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T19:39:31.547969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T19:39:31.547969+00:00'
[2024-12-03T19:39:37.458+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T19:39:37.946+0000] {logging_mixin.py:190} INFO - {"_id": "6707fa42840c437097f7b593", "travel": 3, "payer": 1, "amount": 26092, "code_departure": "SIN", "code_arrival": "ICN", "number_of_passengers": 4, "passengers": [{"passenger": "Zoe Barnaby", "birth_date": "1993-09-24"}, {"name": "Ružica Ivančević", "birth_date": "1995-09-02"}, {"name": "Timm Raabe", "birth_date": "1976-11-19"}, {"name": "Greta Oorschot", "birth_date": "1993-08-19"}], "created": "2024-10-10T16:01:06.102000"}
[2024-12-03T19:39:37.949+0000] {logging_mixin.py:190} INFO - {'_id': '6707fa42840c437097f7b593', 'travel': 3, 'payer': 1, 'amount': 26092, 'code_departure': 'SIN', 'code_arrival': 'ICN', 'number_of_passengers': 4, 'passengers': [{'passenger': 'Zoe Barnaby', 'birth_date': '1993-09-24'}, {'name': 'Ružica Ivančević', 'birth_date': '1995-09-02'}, {'name': 'Timm Raabe', 'birth_date': '1976-11-19'}, {'name': 'Greta Oorschot', 'birth_date': '1993-08-19'}], 'created': '2024-10-10T16:01:06.102000'}
[2024-12-03T19:39:37.950+0000] {logging_mixin.py:190} INFO - Schema: {"type":"record","name":"TravelEvent","namespace":"com.example","fields":[{"name":"_id","type":"string","doc":"Unique identifier for the record"},{"name":"travel","type":"int","doc":"Travel type or identifier"},{"name":"payer","type":"int","doc":"Payer identifier"},{"name":"amount","type":"int","doc":"Payment amount"},{"name":"code_departure","type":"string","doc":"Departure airport code"},{"name":"code_arrival","type":"string","doc":"Arrival airport code"},{"name":"number_of_passengers","type":"int","doc":"Number of passengers in the travel"},{"name":"passengers","type":{"type":"array","items":{"type":"record","name":"Passenger","fields":[{"name":"name","type":"string","doc":"Name of the passenger"},{"name":"birth_date","type":{"type":"string","logicalType":"date"},"doc":"Birth date of the passenger"}]}},"doc":"List of passengers"},{"name":"created","type":{"type":"string","logicalType":"timestamp-millis"},"doc":"Record creation timestamp"}]}
[2024-12-03T19:39:37.952+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1_MongoKafka.py", line 139, in send_data_to_kafka
    if not validate(msg_dict, registered_schema):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastavro/_validation.pyx", line 301, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 310, in fastavro._validation.validate
  File "fastavro/_schema.pyx", line 173, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 267, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: {"type":"record","name":"TravelEvent","namespace":"com.example","fields":[{"name":"_id","type":"string","doc":"Unique identifier for the record"},{"name":"travel","type":"int","doc":"Travel type or identifier"},{"name":"payer","type":"int","doc":"Payer identifier"},{"name":"amount","type":"int","doc":"Payment amount"},{"name":"code_departure","type":"string","doc":"Departure airport code"},{"name":"code_arrival","type":"string","doc":"Arrival airport code"},{"name":"number_of_passengers","type":"int","doc":"Number of passengers in the travel"},{"name":"passengers","type":{"type":"array","items":{"type":"record","name":"Passenger","fields":[{"name":"name","type":"string","doc":"Name of the passenger"},{"name":"birth_date","type":{"type":"string","logicalType":"date"},"doc":"Birth date of the passenger"}]}},"doc":"List of passengers"},{"name":"created","type":{"type":"string","logicalType":"timestamp-millis"},"doc":"Record creation timestamp"}]}
[2024-12-03T19:39:37.981+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=mongo_to_kafka, task_id=send_to_kafka, run_id=manual__2024-12-03T19:39:31.547969+00:00, execution_date=20241203T193931, start_date=20241203T193937, end_date=20241203T193937
[2024-12-03T19:39:38.003+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T19:39:38.004+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 107 for task send_to_kafka ({"type":"record","name":"TravelEvent","namespace":"com.example","fields":[{"name":"_id","type":"string","doc":"Unique identifier for the record"},{"name":"travel","type":"int","doc":"Travel type or identifier"},{"name":"payer","type":"int","doc":"Payer identifier"},{"name":"amount","type":"int","doc":"Payment amount"},{"name":"code_departure","type":"string","doc":"Departure airport code"},{"name":"code_arrival","type":"string","doc":"Arrival airport code"},{"name":"number_of_passengers","type":"int","doc":"Number of passengers in the travel"},{"name":"passengers","type":{"type":"array","items":{"type":"record","name":"Passenger","fields":[{"name":"name","type":"string","doc":"Name of the passenger"},{"name":"birth_date","type":{"type":"string","logicalType":"date"},"doc":"Birth date of the passenger"}]}},"doc":"List of passengers"},{"name":"created","type":{"type":"string","logicalType":"timestamp-millis"},"doc":"Record creation timestamp"}]}; 520)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1_MongoKafka.py", line 139, in send_data_to_kafka
    if not validate(msg_dict, registered_schema):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastavro/_validation.pyx", line 301, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 310, in fastavro._validation.validate
  File "fastavro/_schema.pyx", line 173, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 267, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: {"type":"record","name":"TravelEvent","namespace":"com.example","fields":[{"name":"_id","type":"string","doc":"Unique identifier for the record"},{"name":"travel","type":"int","doc":"Travel type or identifier"},{"name":"payer","type":"int","doc":"Payer identifier"},{"name":"amount","type":"int","doc":"Payment amount"},{"name":"code_departure","type":"string","doc":"Departure airport code"},{"name":"code_arrival","type":"string","doc":"Arrival airport code"},{"name":"number_of_passengers","type":"int","doc":"Number of passengers in the travel"},{"name":"passengers","type":{"type":"array","items":{"type":"record","name":"Passenger","fields":[{"name":"name","type":"string","doc":"Name of the passenger"},{"name":"birth_date","type":{"type":"string","logicalType":"date"},"doc":"Birth date of the passenger"}]}},"doc":"List of passengers"},{"name":"created","type":{"type":"string","logicalType":"timestamp-millis"},"doc":"Record creation timestamp"}]}
[2024-12-03T19:39:38.018+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-03T19:39:38.039+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T19:39:38.041+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
