[2024-12-04T13:11:38.405+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T13:11:38.424+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:11:37.402662+00:00 [queued]>
[2024-12-04T13:11:38.435+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:11:37.402662+00:00 [queued]>
[2024-12-04T13:11:38.437+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T13:11:38.453+0000] {taskinstance.py:2889} INFO - Executing <Task(ConsumeFromTopicOperator): consume> on 2024-12-04 13:11:37.402662+00:00
[2024-12-04T13:11:38.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=375) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T13:11:38.461+0000] {standard_task_runner.py:72} INFO - Started process 376 to run task
[2024-12-04T13:11:38.462+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'consume', 'consume', 'manual__2024-12-04T13:11:37.402662+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/test_dags3.py', '--cfg-path', '/tmp/tmpav0gp0zs']
[2024-12-04T13:11:38.463+0000] {standard_task_runner.py:105} INFO - Job 243: Subtask consume
[2024-12-04T13:11:38.513+0000] {task_command.py:467} INFO - Running <TaskInstance: consume.consume manual__2024-12-04T13:11:37.402662+00:00 [running]> on host bc436253e42c
[2024-12-04T13:11:38.621+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consume' AIRFLOW_CTX_TASK_ID='consume' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T13:11:37.402662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T13:11:37.402662+00:00'
[2024-12-04T13:11:38.622+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T13:11:38.650+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection'
[2024-12-04T13:12:38.655+0000] {consume.py:167} INFO - Reached end of log. Exiting.
[2024-12-04T13:12:38.657+0000] {consume.py:182} INFO - committing offset at end_of_operator
[2024-12-04T13:12:38.690+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T13:12:38.691+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=consume, task_id=consume, run_id=manual__2024-12-04T13:11:37.402662+00:00, execution_date=20241204T131137, start_date=20241204T131138, end_date=20241204T131238
[2024-12-04T13:12:38.722+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T13:12:38.736+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T13:12:38.738+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
