[2024-12-04T13:26:30.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T13:26:30.865+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:26:29.867596+00:00 [queued]>
[2024-12-04T13:26:30.875+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:26:29.867596+00:00 [queued]>
[2024-12-04T13:26:30.876+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T13:26:30.892+0000] {taskinstance.py:2889} INFO - Executing <Task(ConsumeFromTopicOperator): consume> on 2024-12-04 13:26:29.867596+00:00
[2024-12-04T13:26:30.897+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=582) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T13:26:30.899+0000] {standard_task_runner.py:72} INFO - Started process 583 to run task
[2024-12-04T13:26:30.899+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'consume', 'consume', 'manual__2024-12-04T13:26:29.867596+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/test_dags3.py', '--cfg-path', '/tmp/tmpq3ubxdol']
[2024-12-04T13:26:30.900+0000] {standard_task_runner.py:105} INFO - Job 248: Subtask consume
[2024-12-04T13:26:30.949+0000] {task_command.py:467} INFO - Running <TaskInstance: consume.consume manual__2024-12-04T13:26:29.867596+00:00 [running]> on host bc436253e42c
[2024-12-04T13:26:31.059+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consume' AIRFLOW_CTX_TASK_ID='consume' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T13:26:29.867596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T13:26:29.867596+00:00'
[2024-12-04T13:26:31.061+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T13:26:31.088+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection2'
[2024-12-04T13:27:31.584+0000] {consume.py:167} INFO - Reached end of log. Exiting.
[2024-12-04T13:27:31.585+0000] {consume.py:182} INFO - committing offset at end_of_operator
[2024-12-04T13:27:31.608+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T13:27:31.609+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=consume, task_id=consume, run_id=manual__2024-12-04T13:26:29.867596+00:00, execution_date=20241204T132629, start_date=20241204T132630, end_date=20241204T132731
[2024-12-04T13:27:31.659+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T13:27:31.682+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T13:27:31.684+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
