[2024-12-04T22:10:15.060+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T22:10:15.082+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_mongo_to_kafka.mongo_to_kafka manual__2024-12-04T22:10:09.264607+00:00 [queued]>
[2024-12-04T22:10:15.093+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_mongo_to_kafka.mongo_to_kafka manual__2024-12-04T22:10:09.264607+00:00 [queued]>
[2024-12-04T22:10:15.094+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T22:10:15.110+0000] {taskinstance.py:2889} INFO - Executing <Task(ProduceToTopicOperator): mongo_to_kafka> on 2024-12-04 22:10:09.264607+00:00
[2024-12-04T22:10:15.115+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3402) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T22:10:15.117+0000] {standard_task_runner.py:72} INFO - Started process 3403 to run task
[2024-12-04T22:10:15.117+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag1_mongo_to_kafka', 'mongo_to_kafka', 'manual__2024-12-04T22:10:09.264607+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/dag1_MongoKafka.py', '--cfg-path', '/tmp/tmp9u3x0dxn']
[2024-12-04T22:10:15.119+0000] {standard_task_runner.py:105} INFO - Job 307: Subtask mongo_to_kafka
[2024-12-04T22:10:15.715+0000] {task_command.py:467} INFO - Running <TaskInstance: dag1_mongo_to_kafka.mongo_to_kafka manual__2024-12-04T22:10:09.264607+00:00 [running]> on host bc436253e42c
[2024-12-04T22:10:15.811+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_mongo_to_kafka' AIRFLOW_CTX_TASK_ID='mongo_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T22:10:09.264607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T22:10:09.264607+00:00'
[2024-12-04T22:10:15.814+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T22:10:15.843+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection'
[2024-12-04T22:10:15.848+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0x7fe5636e1b20>
[2024-12-04T22:10:17.252+0000] {logging_mixin.py:190} INFO - Извлечено 2 документов из MongoDB
[2024-12-04T22:10:17.254+0000] {logging_mixin.py:190} INFO - {'_id': '6707fa42840c437097f7b593', 'travel': 3, 'payer': 1, 'amount': 26092, 'code_departure': 'SIN', 'code_arrival': 'ICN', 'number_of_passengers': 4, 'passengers': [{'passenger': 'Zoe Barnaby', 'birth_date': '1993-09-24'}, {'name': 'Ružica Ivančević', 'birth_date': '1995-09-02'}, {'name': 'Timm Raabe', 'birth_date': '1976-11-19'}, {'name': 'Greta Oorschot', 'birth_date': '1993-08-19'}], 'created': '2024-10-10T16:01:06.102000'}
[2024-12-04T22:10:17.256+0000] {logging_mixin.py:190} INFO - {'_id': '6707fa469a6e091126308054', 'travel': 1, 'payer': 4, 'amount': 9835, 'code_departure': 'DUB', 'code_arrival': 'BKK', 'number_of_passengers': 1, 'passengers': [{'passenger': 'Carla Jiménez', 'birth_date': '1982-03-11'}], 'created': '2024-10-10T16:01:10.152000'}
[2024-12-04T22:10:17.347+0000] {logging_mixin.py:190} INFO - {'_id': '6707fa42840c437097f7b593', 'travel': 3, 'payer': 1, 'amount': 26092, 'code_departure': 'SIN', 'code_arrival': 'ICN', 'number_of_passengers': 4, 'passengers': [{'passenger': 'Zoe Barnaby', 'birth_date': '1993-09-24'}, {'name': 'Ružica Ivančević', 'birth_date': '1995-09-02'}, {'name': 'Timm Raabe', 'birth_date': '1976-11-19'}, {'name': 'Greta Oorschot', 'birth_date': '1993-08-19'}], 'created': '2024-10-10T16:01:06.102000'}
[2024-12-04T22:10:17.352+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1_MongoKafka.py", line 122, in producer_function
    msg_dict = json.loads(str(value))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2024-12-04T22:10:17.375+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag1_mongo_to_kafka, task_id=mongo_to_kafka, run_id=manual__2024-12-04T22:10:09.264607+00:00, execution_date=20241204T221009, start_date=20241204T221015, end_date=20241204T221017
[2024-12-04T22:10:17.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T22:10:17.393+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 307 for task mongo_to_kafka (Expecting property name enclosed in double quotes: line 1 column 2 (char 1); 3403)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1_MongoKafka.py", line 122, in producer_function
    msg_dict = json.loads(str(value))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2024-12-04T22:10:17.444+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T22:10:17.463+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T22:10:17.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
