[2024-12-09T07:55:36.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T07:55:36.558+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag0_test0.fetch_mongo_data manual__2024-12-09T07:55:34.230853+00:00 [queued]>
[2024-12-09T07:55:36.607+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag0_test0.fetch_mongo_data manual__2024-12-09T07:55:34.230853+00:00 [queued]>
[2024-12-09T07:55:36.609+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T07:55:36.665+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_mongo_data> on 2024-12-09 07:55:34.230853+00:00
[2024-12-09T07:55:36.683+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T07:55:36.689+0000] {standard_task_runner.py:72} INFO - Started process 344 to run task
[2024-12-09T07:55:36.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag0_test0', 'fetch_mongo_data', 'manual__2024-12-09T07:55:34.230853+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag0.py', '--cfg-path', '/tmp/tmpifpslsm3']
[2024-12-09T07:55:36.693+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask fetch_mongo_data
[2024-12-09T07:55:36.794+0000] {task_command.py:467} INFO - Running <TaskInstance: dag0_test0.fetch_mongo_data manual__2024-12-09T07:55:34.230853+00:00 [running]> on host c23cf8b5bd6f
[2024-12-09T07:55:36.947+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag0_test0' AIRFLOW_CTX_TASK_ID='fetch_mongo_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T07:55:34.230853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T07:55:34.230853+00:00'
[2024-12-09T07:55:36.949+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T07:55:36.986+0000] {logging_mixin.py:190} INFO - hell
[2024-12-09T07:55:37.081+0000] {logging_mixin.py:190} INFO - Settings(mongo_url='mongodb+srv://smartintegratordev:YV1ZVX0XbmgGfaq0@cluster0.9kxy2.mongodb.net')
[2024-12-09T07:55:37.082+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T07:55:37.104+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T07:55:37.106+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag0_test0, task_id=fetch_mongo_data, run_id=manual__2024-12-09T07:55:34.230853+00:00, execution_date=20241209T075534, start_date=20241209T075536, end_date=20241209T075537
[2024-12-09T07:55:37.149+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T07:55:37.184+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T07:55:37.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
